require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "says hello to my students"
task :hello do
  p "hello students"
end
